<?php

namespace App\Repositories\Edenred\Mission;

use App\Models\Addworking\Mission\Proposal;
use App\Models\Addworking\Mission\ProposalResponse;
use App\Repositories\Addworking\Common\CommentRepository;
use App\Repositories\Addworking\Mission\ProposalResponseRepository as BaseProposalResponseRepository;
use App\Repositories\Addworking\User\UserRepository;
use App\Repositories\Edenred\Common\AverageDailyRateRepository;
use Illuminate\Http\Request;

class ProposalResponseRepository extends BaseProposalResponseRepository
{
    protected $averageDailyRateRepository;

    public function __construct(
        AverageDailyRateRepository $averageDailyRateRepository,
        CommentRepository $commentRepository,
        UserRepository $userRepository,
        OfferRepository $offerRepository
    ) {
        parent::__construct($commentRepository, $userRepository, $offerRepository);

        $this->averageDailyRateRepository = $averageDailyRateRepository;
    }

    public function createFromRequest(Proposal $proposal, Request $request): ProposalResponse
    {
        $response = parent::createFromRequest($proposal, $request); // TODO: Change the autogenerated stub

        if ($this
            ->averageDailyRateRepository
            ->compareAverageDailyRateToUnitPrice($proposal->offer, $response)
        ) {
            $response->update(['status' => ProposalResponse::STATUS_OK_TO_MEET]);
        }

        return $response;
    }
}
