@th(__('work_field::workfield._table_head.name')."|not_allowed")
@th(__('work_field::workfield._table_head.owner')."|not_allowed")
@th(__('work_field::workfield._table_head.external_id')."|not_allowed|class:text-right")
@th(__('work_field::workfield._table_head.budget')."|not_allowed|class:text-right")
@th(__('work_field::workfield._table_head.starts_at')."|not_allowed")
@th(__('work_field::workfield._table_head.ends_at')."|not_allowed")
@th(__('work_field::workfield._table_head.actions')."|not_allowed|class:text-right")