@th(__('offer::response._table_head.created_at')."|not_allowed")
@th(__('offer::response._table_head.enterprise')."|not_allowed")
@th(__('offer::response._table_head.amount_before_taxes')."|not_allowed")
@th(__('offer::response._table_head.status')."|not_allowed")
@th(__('offer::response._table_head.actions')."|not_allowed|class:text-right")
