@th(__('enterprise.resource.application.views.activity_period._table_head.provider')."|not_allowed")
@th(__('enterprise.resource.application.views.activity_period._table_head.last_name')."|not_allowed|column:last_name")
@th(__('enterprise.resource.application.views.activity_period._table_head.first_name')."|not_allowed|column:first_name")
@th(__('enterprise.resource.application.views.activity_period._table_head.email')."|not_allowed|column:email")
@th(__('enterprise.resource.application.views.activity_period._table_head.start_date')."|column:starts_at|class:text-center")
@th(__('enterprise.resource.application.views.activity_period._table_head.end_date')."|column:ends_at|class:text-center")
@th(__('enterprise.resource.application.views.activity_period._table_head.status')."|not_allowed|column:status|class:text-center")
@th(__('enterprise.resource.application.views.activity_period._table_head.action')."|not_allowed|class:text-right")
