@th(__('billing.outbound.application.views.fee._table_head.number')."|not_allowed")
@th(__('billing.outbound.application.views.fee._table_head.label')."|not_allowed")
@th(__('billing.outbound.application.views.fee._table_head.type')."|not_allowed")
@th(__('billing.outbound.application.views.fee._table_head.service_provider')."|not_allowed")
@th(__('billing.outbound.application.views.fee._table_head.tax_amount_invoice_line')."|not_allowed|class:text-right")
@th(__('billing.outbound.application.views.fee._table_head.amount')."|not_allowed|class:text-right")
@th(__('billing.outbound.application.views.fee._table_head.vat_rate')."|not_allowed|class:text-center")
@th(__('billing.outbound.application.views.fee._table_head.actions')."|not_allowed|class:text-right")