@th(__('document::document.document_type_reject_reason._table_head.number')."|not_allowed")
@th(__('document::document.document_type_reject_reason._table_head.display_name')."|not_allowed")
@th(__('document::document.document_type_reject_reason._table_head.message')."|not_allowed")
@th(__('document::document.document_type_reject_reason._table_head.is_universal')."|not_allowed")
@th(__('document::document.document_type_reject_reason._table_head.actions')."|not_allowed|class:text-right")