@th(__('addworking.components.billing.outbound.payment_order.table_head.number')."|not_allowed")
@th(__('addworking.components.billing.outbound.payment_order.table_head.created_at')."|not_allowed")
@th(__('addworking.components.billing.outbound.payment_order.table_head.executed_at')."|not_allowed")
@th(__('addworking.components.billing.outbound.payment_order.table_head.status')."|not_allowed|class:text-center")
@th(__('addworking.components.billing.outbound.payment_order.table_head.actions')."|not_allowed|class:text-right")
