@th(__('offer::offer._table_head.created_at')."|not_allowed")
@th(__('offer::offer._table_head.label')."|not_allowed")
@th(__('offer::offer._table_head.customer')."|not_allowed")
@th(__('offer::offer._table_head.referent')."|not_allowed")
@th(__('offer::offer._table_head.status')."|not_allowed")
@th(__('offer::offer._table_head.actions')."|not_allowed|class:text-right")
