<?php

return [

    'Départements' => [
         'Ain',
         'Aisne',
         'Allier',
         'Alpes de Haute Provence',
         'Hautes Alpes',
         'Alpes Maritimes',
         'Ardèche',
         'Ardennes',
         'Ariège',
         'Aube',
         'Aude',
         'Aveyron',
         'Bouches du Rhône',
         'Calvados',
         'Cantal',
         'Charente',
         'Charente Maritime',
         'Cher',
         'Corrèze',
         'Corse du Sud',
         'Haute Corse',
         'Côte d\'Or',
         'Côtes d\'Armor',
         'Creuse',
         'Dordogne',
         'Doubs',
         'Drôme',
         'Eure',
         'Eure et Loir',
         'Finistère',
         'Gard',
         'Haute Garonne',
         'Gers',
         'Gironde',
         'Hérault',
         'Ille et Vilaine',
         'Indre',
         'Indre et Loire',
         'Isère',
         'Jura',
         'Landes',
         'Loir et Cher',
         'Loire',
         'Haute Loire',
         'Loire Atlantique',
         'Loiret',
         'Lot',
         'Lot et Garonne',
         'Lozère',
         'Maine et Loire',
         'Manche',
         'Marne',
         'Haute Marne',
         'Mayenne',
         'Meurthe et Moselle',
         'Meuse',
         'Morbihan',
         'Moselle',
         'Nièvre',
         'Nord',
         'Oise',
         'Orne',
         'Pas de Calais',
         'Puy de Dôme',
         'Pyrénées Atlantiques',
         'Hautes Pyrénées',
         'Pyrénées Orientales',
         'Bas Rhin',
         'Haut Rhin',
         'Rhône',
         'Haute Saône',
         'Saône et Loire',
         'Sarthe',
         'Savoie',
         'Haute Savoie',
         'Paris',
         'Seine Maritime',
         'Seine et Marne',
         'Yvelines',
         'Deux Sèvres',
         'Somme',
         'Tarn',
         'Tarn et Garonne',
         'Var',
         'Vaucluse',
         'Vendée',
         'Vienne',
         'Haute Vienne',
         'Vosges',
         'Yonne',
         'Territoire de Belfort',
         'Essonne',
         'Hauts de Seine',
         'Seine St Denis',
         'Val de Marne',
         'Val d\'Oise',
         'DOM',
         'Guadeloupe',
         'Martinique',
         'Guyane',
         'Réunion',
         'Saint Pierre et Miquelon',
         'Mayotte',
    ],

    'Régions' => [
        "Alsace",
        "Aquitaine",
        "Auvergne",
        "Basse-Normandie",
        "Bourgogne",
        "Bretagne",
        "Centre-Val de Loire",
        "Champagne-Ardenne",
        "Corse",
        "Franche-Comté",
        "Guadeloupe",
        "Guyane",
        "Haute-Normandie",
        "Île-de-France",
        "La Réunion",
        "Languedoc-Roussillon",
        "Limousin",
        "Lorraine",
        "Martinique",
        "Mayotte",
        "Midi-Pyrénées",
        "Nord-Pas-de-Calais",
        "Pays de la Loire",
        "Picardie",
        "Poitou-Charentes",
        "Provence-Alpes-Côte d'Azur",
        "Rhône-Alpes",
    ],

    'Europe' => [
        "Allemagne",
        "Autriche",
        "Belgique",
        "Bulgarie",
        "Chypre",
        "Croatie",
        "Danemark",
        "Espagne",
        "Estonie",
        "Finlande",
        "Grèce",
        "Hongrie",
        "Irlande",
        "Italie",
        "Lettonie",
        "Lituanie",
        "Luxembourg",
        "Malte",
        "Monaco",
        "Pays-Bas",
        "Pologne",
        "Portugal",
        "République Tchèque",
        "Roumanie",
        "Royaume-Uni",
        "Slovaquie",
        "Slovénie",
        "Suède",
        "Suisse",
    ],

    'Autres pays' => [
        "Afrique du Sud",
        "Albanie",
        "Algérie",
        "Andorra",
        "Antilles néerlandaises",
        "Arabie Saoudite",
        "Argentine",
        "Australie",
        "Autres",
        "Bahamas",
        "Bahreïn",
        "Bénin",
        "Bermudes",
        "Biélorussie",
        "Bolivie",
        "Bosnie-Herzégovine",
        "Botswana",
        "Brésil",
        "Brunei",
        "Burkina Faso",
        "Burundi",
        "Cambodge",
        "Cameroun",
        "Canada",
        "Cap Vert",
        "Chili",
        "Chine",
        "Cité du Vatican",
        "Colombie",
        "Comores",
        "Congo",
        "Corée du Nord",
        "Corée du Sud",
        "Costa Rica",
        "Côte d'Ivoire",
        "Cuba",
        "Djibouti",
        "Dominique",
        "Egypte",
        "Emirats Arabes Unis",
        "Equateur",
        "Erythrée",
        "Etats Fédérés de Micronésie",
        "Etats-Unis",
        "Ethiopie",
        "Fédération de Russie",
        "Fidji",
        "Gabon",
        "Gambie",
        "Géorgie",
        "Ghana",
        "Gibraltar",
        "Grenade",
        "Groenland",
        "Guam",
        "Guatemala",
        "Guernesey",
        "Guinée",
        "Guinée équatoriale",
        "Guinée-Bissau",
        "Guyana",
        "Guyane française",
        "Haïti",
        "Honduras",
        "Hong Kong",
        "Île Bouvet",
        "Île Christmas",
        "Île de Man",
        "Île Heard et îles McDonald",
        "Îles Alan",
        "Îles Caïman",
        "Îles Cocos",
        "Îles Cook",
        "Îles de Géorgie du Sud et Sandwich du Sud",
        "Îles Féroé",
        "Îles Malouines",
        "Îles Mariannes du nord",
        "Îles Marshall",
        "Îles Salomon",
        "Îles Turques et Caïques",
        "Îles Vierges",
        "Inde",
        "Indonésie",
        "Irak",
        "Iran",
        "Islande",
        "Israël",
        "Jamaïque",
        "Japon",
        "Jersey",
        "Jordanie",
        "Kenya",
        "Kosovo",
        "Koweit",
        "Laos",
        "Lesotho",
        "Liban",
        "Liberia",
        "Libye",
        "Liechtenstein",
        "Macao",
        "Macédonie",
        "Madagascar",
        "Malaisie",
        "Malawi",
        "Maldives",
        "Mali",
        "Maroc",
        "Maurice",
        "Mauritanie",
        "Mayotte",
        "Mexique",
        "Moldavie",
        "Mongolie",
        "Monténégro",
        "Montserrat",
        "Mozambique",
        "Myanmar",
        "Namibie",
        "Nations caribéennes",
        "Nauru",
        "Népal",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "Niue",
        "Norfolk",
        "Norvège",
        "Nouvelle-Calédonie",
        "Nouvelle-Zélande",
        "Oman",
        "Ouganda",
        "Pakistan",
        "Palau",
        "Panama",
        "Papouasie-Nouvelle-Guinée",
        "Paraguay",
        "Pérou",
        "Philippines",
        "Pitcairn",
        "Polynésie française",
        "Porto Rico",
        "Qatar",
        "République Centrafricaine",
        "République Démocratique du Congo",
        "République Dominicaine",
        "Rwanda",
        "Sahara Occidental",
        "Saint Christophe et Niévès",
        "Saint Marin",
        "Saint Pierre et Miquelon",
        "Saint Vincent et les Grenadines",
        "Sainte Hélène",
        "Sainte Lucie",
        "Salvador",
        "Samoa",
        "Sao Tomé et Principe",
        "Sénégal",
        "Serbie",
        "Serbie et Monténégro",
        "Seychelles",
        "Sierra Leone",
        "Singapour",
        "Somalie",
        "Soudan",
        "Soudan du Sud",
        "Sri Lanka",
        "Suriname",
        "Swaziland",
        "Syrie",
        "Tadjikistan",
        "Taïwan",
        "Tanzanie",
        "Tchad",
        "Territoires Français du Sud",
        "Territoires Britannique de l'Océan Indien",
        "Territoires Palestiniens",
        "Thaïlande",
        "Timor Oriental",
        "Togo",
        "Tokelau",
        "Tonga",
        "Trinité et Tobago",
        "Tunisie",
        "Turkménistan",
        "Turquie",
        "Tuvalu",
        "Ukraine",
        "Uruguay",
        "Vanuatu",
        "Venezuela",
        "Vietnam",
        "Wallis et Futuna",
        "Yémen",
        "Zambie",
        "Zimbabwe",
    ],

];
