@th(__('components.contract.contract.application.views.annex._table_head.number')."|not_allowed")
@th(__('components.contract.contract.application.views.annex._table_head.name')."|not_allowed")
@th(__('components.contract.contract.application.views.annex._table_head.description')."|not_allowed")
@th(__('components.contract.contract.application.views.annex._table_head.created_at')."|not_allowed")
@th(__('components.contract.contract.application.views.annex._table_head.file')."|not_allowed")
@th(__('components.contract.contract.application.views.annex._table_head.actions')."|not_allowed|class:text-right")
