@th(__('components.contract.model.application.views.contract_model_part._table_head.id')."|not_allowed")
@th(__('components.contract.model.application.views.contract_model_part._table_head.display_name')."|not_allowed")
@th(__('components.contract.model.application.views.contract_model_part._table_head.order')."|not_allowed")
@th(__('components.contract.model.application.views.contract_model_part._table_head.is_initialled')."|not_allowed")
@th(__('components.contract.model.application.views.contract_model_part._table_head.is_signed')."|not_allowed")
@th(__('components.contract.model.application.views.contract_model_part._table_head.actions')."|not_allowed")
