@th(__('components.contract.model.application.views.contract_model._table_head.number')."|not_allowed")
@th(__('components.contract.model.application.views.contract_model._table_head.status')."|not_allowed")
@th(__('components.contract.model.application.views.contract_model._table_head.enterprise')."|not_allowed")
@th(__('components.contract.model.application.views.contract_model._table_head.display_name')."|not_allowed")
@th(__('components.contract.model.application.views.contract_model._table_head.actions')."|not_allowed|class:text-right")
